apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
        # resources:
        #   requests:
        #     cpu: 250m
        #   limits:
        #     cpu: 500m 
      - name : azure-vote-front
        image: whujin11e/public:azure_voting_app
        env:
        - name: STRESS_SECS
          value: "0"
        - name: REDIS
          value: "azure-vote-back"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
               name: redis
               key: REDIS_PWD