apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - name : azure-vote-front
        image: whujin11e/public:azure_voting_app
        env:
        - name: STRESS_SECS
          value: "2"
        - name: REDIS
          value: "azure-vote-back"
        - name: REDIS_PWD
          value: "$(REDIS_PWD)"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
               name: redis
               key: REDIS_PWD